### ISSUE TITLE
启用主题后，打开不了有评论的文章

### ISSUE THREAD

**Issue by novohit** [anghunk/typecho-anghunk#11]
没有评论的文章可以正常打开，一旦添加评论后就无法打开会显示如下页面

![image](https://user-images.githubusercontent.com/101090395/183689925-7a0e1f84-1083-42e9-83db-31015b614527.png)

**Comment by zburu** [comment]
@zhuweixiong22   需要禁用 php 环境中的 iconv 函数

如果你使用宝塔搭建的话，在软件商店，在安装的php下点击设置，找到禁用函数，将 iconv 删除

**Comment by zhuweixiong22** [comment]
> @zhuweixiong22 需要禁止php环境中的iconv函数
> 
> 如果你使用宝塔社区安装的话，在软件商店，在php下点击设置，找到禁用函数，将图标删除
我使用的是docker部署
刚刚发现如果关闭ip地址显示就能正常访问，打开访问有评论的文章就会这样

**Comment by zburu** [comment]
> > @zhuweixiong22 需要禁止php环境中的iconv函数
> > 
> > 如果你使用宝塔社区安装的话，在软件商店，在php下点击设置，找到禁用函数，将图标删除
> 我使用的是docker部署
> 刚刚发现如果关闭ip地址显示就能正常访问，打开访问有评论的文章就会这样

明天我排查一下，ip显示不应该不会影响评论功能
